apiVersion: v1
kind: Namespace
metadata:
  name: backup-enterprise
  labels:
    name: backup-enterprise
    environment: production
    app.kubernetes.io/name: intelligent-backup
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: namespace
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: backup-resource-quota
  namespace: backup-enterprise
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    persistentvolumeclaims: "10"
    services: "5"
    secrets: "10"
    configmaps: "10"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: backup-limit-range
  namespace: backup-enterprise
spec:
  limits:
  - default:
      cpu: "1"
      memory: 2Gi
    defaultRequest:
      cpu: "0.5"
      memory: 1Gi
    type: Container
  - default:
      storage: 10Gi
    type: PersistentVolumeClaim